ssh:
  host: ${SSH_HOST}
  user: ${SSH_USER}
  port: ${SSH_PORT}
  pem: ${SSH_PEM}
  database-port: ${SSH_DATABASE_PORT}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: ${GITHUB_REDIRECT_URI}
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope:
              - profile
              - email
  cloud:
    aws:
      credentials:
        access-key: ${AWS_S3_IAM_ACCESS_KEY}
        secret-key: ${AWS_S3_IAM_SECRET_KEY}
      s3:
        bucket: ${AWS_S3_BUCKET}
      region:
        static: ap-northeast-2
      stack:
        auto: false

jwt:
  secret:
    access-secret-key: ${JWT_ACCESS_SECRET}
  token:
    access-expiration: 3600000 # 1시간(1000(ms) * 60(m) * 60(h))
    access-header: Authorization

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
  api-docs:
    groups:
      enabled: true